[TH2-4566] Owasp dependency check build step
th2-net/th2-lw-data-provider pull request #21
Opened 2023-02-07 08:10 UTC by isengrims

2023-02-07 08:29 UTC, OptimumOpium requested changes

2023-02-07 10:47 UTC, OptimumOpium approved these changes

2023-02-14 07:47 UTC, OptimumOpium requested changes

2023-02-14 07:47 UTC, OptimumOpium commented on .github/workflows/build.yml
> +    runs-on: ubuntu-20.04
You can reuse job from our corporate workflows. There were changes to support multiprojects

2023-02-14 07:47 UTC, OptimumOpium commented on build.gradle
>  }
You need to apply the plugin and configure the task only for the root project.

2023-03-06 07:47 UTC, OptimumOpium requested changes

2023-03-06 07:47 UTC, OptimumOpium commented on .github/workflows/build.yml
> +                - 'grpc/gradle.properties'
I don't think this  work when you use `uses` directive.
Probably you wanted this:
```suggestion
  changes:
      name: Collect changed files
      runs-on: ubuntu-20.04
      outputs:
        app: ${{ steps.filter.outputs.app }}
        grpc: ${{ steps.filter.outputs.grpc }}
      steps:
        - uses: dorny/paths-filter@v2
          id: filter
          with:
            filters: |
              app:
                - 'gradle.properties'
              grpc:
                - 'grpc/gradle.properties'
```

2023-03-06 07:47 UTC, OptimumOpium commented on build.gradle
> +}
Please, move this into `buildSrc/src/main/groovy/com.exactpro.th2.common-convensions.gradle`

2023-03-06 07:47 UTC, OptimumOpium commented on grpc/build.gradle
>  }
Will be applied from `buildSrc/src/main/groovy/com.exactpro.th2.common-convensions.gradle`

2023-03-06 07:47 UTC, OptimumOpium commented on grpc/build.gradle
> +            srcDirs 'proto'
Have you moved proto files into that directory?
You could look at this repo as an example: https://github.com/th2-net/th2-read-db/tree/dev/grpc

2023-03-09 09:21 UTC, OptimumOpium commented on grpc/build.gradle
>  }
Can be removed because the directory is located in `build` folder

2023-03-09 09:21 UTC, OptimumOpium commented on grpc/gradle.properties
> +version_suffix=
No need to add this. It will be taken from root gradle.properties

2023-03-09 09:23 UTC, OptimumOpium commented on grpc/build.gradle
>              srcDirs 'src/main/proto'
Please, correct the project's structure as it was done in https://github.com/th2-net/th2-read-db/tree/dev/grpc

2023-03-09 09:55 UTC, OptimumCode commented on grpc/proto/th2_grpc_lw_data_provider/lw_data_provider.proto
> + * Copyright 2020-2020 Exactpro (Exactpro Systems Limited)
Please, update copyright

2023-03-09 09:55 UTC, OptimumCode commented on grpc/proto/th2_grpc_lw_data_provider/lw_data_provider.proto
> +/*
Have you changed the formatting? Why the file is changed completely?

2023-03-09 11:02 UTC, OptimumOpium approved these changes

2023-03-09 11:16 UTC, merged