Update gradle.properties
th2-net/th2-lw-data-provider pull request #83
Opened 2024-05-17 11:30 UTC by Nikita-Smirnov-Exactpro

TH2-1836-license-check

2024-05-30 12:34 UTC, OptimumCode requested changes
issue: please, update the version for `utils` project

2024-05-30 12:34 UTC, OptimumCode commented on gradle.properties
> +
chore: please, remove all redundant lines

2024-05-31 09:54 UTC, Nikita-Smirnov-Exactpro commented
> issue: please, update the version for `utils` project

solved

2024-06-02 11:00 UTC, OptimumCode approved these changes

2024-06-03 10:05 UTC, merged